### PR TITLE
Add a reference to our data and processing template repos.

### PR DESCRIPTION
**Pull request by nekhtiari**
Pull Request
============

> Tracked in JIRA by [IN-XXX](https://geoinformationstore.atlassian.net/browse/IN-XXX)
> Paired with @a, @b

### Scope of the PR

Added a sentence referring to our data and processing template repo.

### Checklist

- [x] Checked spelling and grammar
- [ ] Provided code samples where relevant
- [x] Checked the output of `make html` to ensure new content displays correctly

### CODE REVIEW

**Review by teoEnache — APPROVED** [review]
LGTM. Thank you

**Review by rodrigoalmeida94 — APPROVED** [review]
Cool!

**Review by marooned20 — COMMENTED** [review]
💪  LGTM

**Review by perusio — APPROVED** [review]
LGTM.

**Review by chrieke — APPROVED** [review]

**Review by markusuwe — APPROVED** [review]
Nice!

**Pull request merged**
